{% set name = "opentelemetry-exporter-zipkin-json" %}
{% set version = "1.15.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_exporter_zipkin_json-{{ version }}.tar.gz
  sha256: 600497594541a8a69c55ab94bf0aad07e8ab6bbce3dbcde8f3f5eda06a903d5c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling
  run:
    - python >=3.7
    - opentelemetry-api >=1.3,<2.dev0
    - opentelemetry-sdk >=1.11,<2.dev0
    - requests >=2.7,<3.dev0

test:
  imports:
    - opentelemetry
    - opentelemetry.exporter
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python/tree/main/exporter/opentelemetry-exporter-zipkin-json
  summary: Zipkin Span JSON Exporter for OpenTelemetry
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
